version: '3.8'

services:
    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: minecraft_servers
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - minecraft_backend

    redis:
        image: redis:7-alpine
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        networks:
            - minecraft_backend

volumes:
    postgres_data:
    redis_data:

networks:
    minecraft_backend:
        driver: bridge
